export interface WorkItemDefinition {
  name: string;
  code: number;
}

export interface WorkCategoryDefinition {
  name: string;
  code: number;
  workItems: WorkItemDefinition[];
}

export interface ProjectTypeWorkItemDefinition {
  projectType: string;
  description: string;
  categories: WorkCategoryDefinition[];
}

export type SeedProjectWorkItemsType = ProjectTypeWorkItemDefinition[];

export const SeedProjectWorkItems: SeedProjectWorkItemsType = [
  {
    projectType: 'Residential Construction',
    description: 'Work items related to residential construction projects',
    categories: [
      {
        name: 'Pre-Construction',
        code: 10,
        workItems: [
          { name: 'Blueprints', code: 5 },
          { name: 'Plot Plan, Stake Out, Pinning', code: 10 },
          { name: 'Zoning Permit', code: 15 },
          { name: 'Building Permit', code: 20 },
          { name: 'Water Tap Fee', code: 21 },
          { name: 'Port-O-Let', code: 25 },
          { name: 'Temporary Electric', code: 30 },
          { name: 'Clearing', code: 35 },
          { name: 'Design Fee', code: 40 },
        ],
      },
      {
        name: 'Site Work',
        code: 20,
        workItems: [
          { name: 'Foundation Excavation', code: 5 },
          { name: 'Trench Footers', code: 6 },
          { name: 'Footer Labor', code: 10 },
          { name: 'Footer Concrete', code: 15 },
          { name: 'Pump Truck - Footer', code: 20 },
          { name: 'Drain Tile Material', code: 25 },
          { name: 'Footer Gravel Material', code: 30 },
          { name: 'Footer Gravel - Slinger', code: 35 },
          { name: 'Foundation Wall Labor', code: 40 },
          { name: 'Block Material', code: 41 },
          { name: 'Block Labor', code: 42 },
          { name: 'Under Slab Insulation Material', code: 43 },
          { name: 'Foundation Wall Concrete', code: 45 },
          { name: 'Pump Truck - Wall', code: 46 },
          { name: 'Waterproof Foundation', code: 50 },
          { name: 'Gravel To Top Off Footer', code: 55 },
          { name: 'Plumbing Underground', code: 60 },
          { name: 'Backfill Foundation', code: 65 },
          { name: 'Haul Excess Dirt', code: 70 },
          { name: 'Garage/Porch/Temp Drive Gravel', code: 75 },
          { name: 'Basement & Garage Slab Labor', code: 80 },
          { name: 'Basement & Garage Slab Concrete', code: 85 },
          { name: 'Basement & Garage Slab Rebar/Plastic', code: 90 },
          { name: 'Pump Truck - Slabs', code: 95 },
        ],
      },
      {
        name: 'Framing & Rough-in',
        code: 30,
        workItems: [
          { name: 'Framing Labor', code: 5 },
          { name: 'Framing Material', code: 10 },
          { name: 'Truss Material', code: 15 },
          { name: 'Framing Material Pickups', code: 20 },
          { name: 'Dumpsters', code: 25 },
          { name: 'Shingle Labor', code: 30 },
          { name: 'Shingle Material', code: 35 },
          { name: 'Metal Roof Material', code: 40 },
          { name: 'Metal Roof Labor', code: 45 },
          { name: 'Window Install Material & Labor', code: 50 },
          { name: 'Front Door Material', code: 55 },
          { name: 'Exterior Door Material', code: 60 },
          { name: 'Exterior Door Labor', code: 65 },
          { name: 'HVAC Rough', code: 70 },
          { name: 'Fireplace Install', code: 75 },
          { name: 'Plumbing Rough', code: 80 },
          { name: 'Sewer & Water Tap Fee', code: 85 },
          { name: 'Sewer & Water Install', code: 90 },
          { name: 'Sewer/Water Gravel Material', code: 95 },
          { name: 'Electric Trench & Sump Line', code: 100 },
          { name: 'Frame Punch Material', code: 105 },
          { name: 'Electric Rough', code: 110 },
          { name: 'Low Voltage Rough', code: 115 },
          { name: 'AIP', code: 120 },
          { name: 'Insulation', code: 125 },
        ],
      },
      {
        name: 'Exterior',
        code: 40,
        workItems: [
          { name: 'Exterior Trim Labor', code: 5 },
          { name: 'Exterior Trim Material', code: 10 },
          { name: 'Paint Exterior Labor', code: 15 },
          { name: 'Paint Exterior Material', code: 20 },
          { name: 'Install Garage Doors', code: 25 },
          { name: 'Garage Door Opener Material', code: 30 },
          { name: 'Garage Door Opener Labor', code: 35 },
          { name: 'Install Brick Flashing', code: 40 },
          { name: 'Brick Labor', code: 45 },
          { name: 'Brick Material', code: 50 },
          { name: 'Stone Labor', code: 55 },
          { name: 'Stone Labor', code: 60 },
          { name: 'Clean Brick', code: 65 },
          { name: 'Deck Labor', code: 70 },
          { name: 'Deck Material', code: 75 },
          { name: 'Deck Rails', code: 80 },
          { name: 'Gutters', code: 85 },
          { name: 'Exterior Concrete Labor', code: 90 },
          { name: 'Exterior Concrete Gravel', code: 95 },
          { name: 'Exterior Concrete', code: 100 },
          { name: 'Exterior Concrete Rebar', code: 105 },
          { name: 'Boulder Labor', code: 110 },
          { name: 'Boulders Material', code: 115 },
          { name: 'Final Grade', code: 120 },
          { name: 'Install Landscaping', code: 125 },
          { name: 'Install Irrigation System', code: 130 },
          { name: 'Install Landscape Lighting', code: 135 },
          { name: 'Install Sod', code: 140 },
          { name: 'Install Fence', code: 145 },
          { name: 'Mailbox', code: 150 },
          { name: 'Install Phantom Screens', code: 155 },
          { name: 'Pressure Wash Exterior Concrete', code: 160 },
        ],
      },
      {
        name: 'Interior Install',
        code: 50,
        workItems: [
          { name: 'Drywall Material', code: 5 },
          { name: 'Hang Drywall Labor', code: 10 },
          { name: 'Finish Drywall Labor', code: 15 },
          { name: 'Prime Walls Labor', code: 20 },
          { name: 'Prime Walls Material', code: 25 },
          { name: 'Attic Blow', code: 30 },
          { name: 'Master Shower Tile Labor', code: 35 },
          { name: 'Master Shower Tile Material', code: 40 },
          { name: 'Guest Showers Tile Labor', code: 45 },
          { name: 'Guest Shower Tile Material', code: 50 },
          { name: 'Tile Floors Labor', code: 55 },
          { name: 'Tile Floors Material', code: 60 },
          { name: 'Shower Doors', code: 65 },
          { name: 'Interior Trim Labor', code: 70 },
          { name: 'Interior Trim/Doors Material', code: 75 },
          { name: 'Vanity Material', code: 80 },
          { name: 'Cabinet Material', code: 85 },
          { name: "Interior Trim Extra's Material", code: 90 },
          { name: 'Interior Rails', code: 95 },
          { name: 'HVAC Final', code: 100 },
          { name: 'Electric Final', code: 105 },
          { name: 'Electric Final Materials', code: 110 },
        ],
      },
      {
        name: 'Interior Final',
        code: 60,
        workItems: [
          { name: 'Spray Interior Trim/Doors Labor', code: 5 },
          { name: 'Spray Interior Trim/Doors Material', code: 10 },
          { name: 'Drywall Touch Up', code: 15 },
          { name: 'Roll Walls Labor', code: 20 },
          { name: 'Roll Walls Material', code: 25 },
          { name: 'Flooring Labor', code: 30 },
          { name: 'Flooring Material', code: 35 },
          { name: 'Countertops', code: 40 },
          { name: 'Interior Trim Final Labor', code: 45 },
          { name: 'Interior Trim Final Materials', code: 50 },
          { name: 'Cabinet Hardware', code: 55 },
          { name: 'Backsplash Labor', code: 60 },
          { name: 'Backsplash Material', code: 65 },
          { name: 'Plumbing Final', code: 70 },
          { name: 'Plumbing Final Material', code: 75 },
          { name: 'Mirrors', code: 80 },
          { name: 'Shelves', code: 85 },
          { name: 'Basement Drape Insulation', code: 90 },
          { name: 'Carpet Prep Labor', code: 95 },
          { name: 'Carpet Install', code: 100 },
          { name: 'Carpet Material', code: 105 },
          { name: 'Appliances', code: 110 },
          { name: 'Initial Construction Clean', code: 115 },
          { name: 'Punchout Labor', code: 120 },
          { name: 'Punchout Materials', code: 125 },
          { name: 'Pressure Wash Basement', code: 130 },
          { name: 'Final Construction Clean', code: 135 },
        ],
      },
      {
        name: 'Overhead',
        code: 70,
        workItems: [
          { name: 'Tools', code: 5 },
          { name: 'Service', code: 10 },
        ],
      },
      {
        name: 'Income',
        code: 80,
        workItems: [
          { name: 'Bank Draw', code: 5 },
          { name: 'Change Order', code: 10 },
        ],
      },
    ],
  },
];
