import { JobCategoryItemEntry } from '@/models/jobCategoryItemEntry';

// Simulate an async function to load JSON data (like fetching from an API or reading from a file)
const ALLJOBCATEGORYITEMS: JobCategoryItemEntry[] = [
  {
    projectId: 1,
    categoryName: 'Pre-Construction',
    itemName: 'Sewer Permit',
    bidPrice: 1500,
    spentToDate: 800,
    categoryComplete: false,
  },
  {
    projectId: 2,
    categoryName: 'Pre-Construction',
    itemName: 'Building Permit',
    bidPrice: 3000,
    spentToDate: 2000,
    categoryComplete: false,
  },
  {
    projectId: 3,
    categoryName: 'Pre-Construction',
    itemName: 'Sewer Permit',
    bidPrice: 5000,
    spentToDate: 4500,
    categoryComplete: true,
  },
  {
    projectId: 4,
    categoryName: 'Pre-Construction',
    itemName: 'Building Permit',
    bidPrice: 7500,
    spentToDate: 6000,
    categoryComplete: true,
  },
  {
    projectId: 5,
    categoryName: 'Pre-Construction',
    itemName: 'Sewer Permit',
    bidPrice: 12000,
    spentToDate: 7000,
    categoryComplete: false,
  },
  {
    projectId: 6,
    categoryName: 'Pre-Construction',
    itemName: 'Building Permit',
    bidPrice: 15000,
    spentToDate: 3000,
    categoryComplete: false,
  },
  {
    projectId: 7,
    categoryName: 'Pre-Construction',
    itemName: 'Sewer Permit',
    bidPrice: 20000,
    spentToDate: 1000,
    categoryComplete: true,
  },
  {
    projectId: 8,
    categoryName: 'Pre-Construction',
    itemName: 'Building Permit',
    bidPrice: 35000,
    spentToDate: 5000,
    categoryComplete: false,
  },
  {
    projectId: 9,
    categoryName: 'Pre-Construction',
    itemName: 'Sewer Permit',
    bidPrice: 40000,
    spentToDate: 6500,
    categoryComplete: true,
  },
  {
    projectId: 1,
    categoryName: 'Site Work',
    itemName: 'Silt Fence',
    bidPrice: 1500,
    spentToDate: 800,
    categoryComplete: false,
  },
  {
    projectId: 2,
    categoryName: 'Site Work',
    itemName: 'Basement Excavation',
    bidPrice: 3000,
    spentToDate: 2000,
    categoryComplete: false,
  },
  {
    projectId: 3,
    categoryName: 'Site Work',
    itemName: 'Site Grading',
    bidPrice: 5000,
    spentToDate: 450,
    categoryComplete: true,
  },
  {
    projectId: 4,
    categoryName: 'Site Work',
    itemName: 'Silt Fence',
    bidPrice: 8000,
    spentToDate: 600,
    categoryComplete: true,
  },
  {
    projectId: 5,
    categoryName: 'Site Work',
    itemName: 'Basement Excavation',
    bidPrice: 12000,
    spentToDate: 7000,
    categoryComplete: false,
  },
  {
    projectId: 6,
    categoryName: 'Site Work',
    itemName: 'Site Grading',
    bidPrice: 15000,
    spentToDate: 3000,
    categoryComplete: false,
  },
  {
    projectId: 7,
    categoryName: 'Site Work',
    itemName: 'Silt Fence',
    bidPrice: 20000,
    spentToDate: 1000,
    categoryComplete: true,
  },
  {
    projectId: 8,
    categoryName: 'Site Work',
    itemName: 'Basement Excavation',
    bidPrice: 35000,
    spentToDate: 5000,
    categoryComplete: false,
  },
  {
    projectId: 9,
    categoryName: 'Site Work',
    itemName: 'Site Grading',
    bidPrice: 40000,
    spentToDate: 6500,
    categoryComplete: true,
  },

  {
    projectId: 1,
    categoryName: 'Framing',
    itemName: 'Wall Framing',
    bidPrice: 2000,
    spentToDate: 750,
    categoryComplete: false,
  },
  {
    projectId: 2,
    categoryName: 'Framing',
    itemName: 'Roof',
    bidPrice: 4000,
    spentToDate: 2500,
    categoryComplete: false,
  },
  {
    projectId: 3,
    categoryName: 'Framing',
    itemName: 'Decks',
    bidPrice: 6000,
    spentToDate: 5500,
    categoryComplete: true,
  },
  {
    projectId: 4,
    categoryName: 'Framing',
    itemName: 'Install Windows',
    bidPrice: 8000,
    spentToDate: 400,
    categoryComplete: true,
  },
  {
    projectId: 5,
    categoryName: 'Framing',
    itemName: 'Wall Framing',
    bidPrice: 10000,
    spentToDate: 6500,
    categoryComplete: false,
  },
  {
    projectId: 6,
    categoryName: 'Framing',
    itemName: 'Roof',
    bidPrice: 15000,
    spentToDate: 3000,
    categoryComplete: false,
  },
  {
    projectId: 7,
    categoryName: 'Framing',
    itemName: 'Decks',
    bidPrice: 18000,
    spentToDate: 850,
    categoryComplete: true,
  },
  {
    projectId: 8,
    categoryName: 'Framing',
    itemName: 'Install Windows',
    bidPrice: 25000,
    spentToDate: 5000,
    categoryComplete: false,
  },
  {
    projectId: 9,
    categoryName: 'Framing',
    itemName: 'Wall Framing',
    bidPrice: 35000,
    spentToDate: 6000,
    categoryComplete: true,
  },
  {
    projectId: 1,
    categoryName: 'Exterior Finishes',
    itemName: 'Exterior Painting',
    bidPrice: 1500,
    spentToDate: 800,
    categoryComplete: false,
  },
  {
    projectId: 2,
    categoryName: 'Exterior Finishes',
    itemName: 'Siding',
    bidPrice: 2500,
    spentToDate: 2000,
    categoryComplete: false,
  },
  {
    projectId: 3,
    categoryName: 'Exterior Finishes',
    itemName: 'Install Windows',
    bidPrice: 5000,
    spentToDate: 4500,
    categoryComplete: true,
  },
  {
    projectId: 4,
    categoryName: 'Exterior Finishes',
    itemName: 'Shutters',
    bidPrice: 7000,
    spentToDate: 600,
    categoryComplete: true,
  },
  {
    projectId: 5,
    categoryName: 'Exterior Finishes',
    itemName: 'Exterior Painting',
    bidPrice: 12000,
    spentToDate: 700,
    categoryComplete: false,
  },
  {
    projectId: 6,
    categoryName: 'Exterior Finishes',
    itemName: 'Siding',
    bidPrice: 15000,
    spentToDate: 3000,
    categoryComplete: false,
  },
  {
    projectId: 7,
    categoryName: 'Exterior Finishes',
    itemName: 'Install Windows',
    bidPrice: 20000,
    spentToDate: 1000,
    categoryComplete: true,
  },
  {
    projectId: 8,
    categoryName: 'Exterior Finishes',
    itemName: 'Shutters',
    bidPrice: 35000,
    spentToDate: 5000,
    categoryComplete: false,
  },
  {
    projectId: 9,
    categoryName: 'Exterior Finishes',
    itemName: 'Exterior Painting',
    bidPrice: 40000,
    spentToDate: 6500,
    categoryComplete: true,
  },
  {
    projectId: 1,
    categoryName: 'Interior Finishes',
    itemName: 'Painting',
    bidPrice: 1500,
    spentToDate: 8000,
    categoryComplete: false,
  },
  {
    projectId: 2,
    categoryName: 'Interior Finishes',
    itemName: 'Carpet',
    bidPrice: 2500,
    spentToDate: 2000,
    categoryComplete: false,
  },
  {
    projectId: 3,
    categoryName: 'Interior Finishes',
    itemName: 'Laminate Flooring',
    bidPrice: 5000,
    spentToDate: 4500,
    categoryComplete: true,
  },
  {
    projectId: 4,
    categoryName: 'Interior Finishes',
    itemName: 'Hardwood Flooring',
    bidPrice: 7000,
    spentToDate: 6000,
    categoryComplete: true,
  },
  {
    projectId: 5,
    categoryName: 'Interior Finishes',
    itemName: 'Painting',
    bidPrice: 12000,
    spentToDate: 7000,
    categoryComplete: false,
  },
  {
    projectId: 6,
    categoryName: 'Interior Finishes',
    itemName: 'Carpet',
    bidPrice: 15000,
    spentToDate: 3000,
    categoryComplete: false,
  },
  {
    projectId: 7,
    categoryName: 'Interior Finishes',
    itemName: 'Laminate Flooring',
    bidPrice: 20000,
    spentToDate: 1000,
    categoryComplete: true,
  },
  {
    projectId: 8,
    categoryName: 'Interior Finishes',
    itemName: 'Hardwood Flooring',
    bidPrice: 35000,
    spentToDate: 5000,
    categoryComplete: false,
  },
  {
    projectId: 9,
    categoryName: 'Interior Finishes',
    itemName: 'Painting',
    bidPrice: 40000,
    spentToDate: 650,
    categoryComplete: true,
  },
  {
    projectId: 1,
    categoryName: 'Mechanical',
    itemName: 'Furnace',
    bidPrice: 2500,
    spentToDate: 8000,
    categoryComplete: false,
  },
  {
    projectId: 2,
    categoryName: 'Mechanical',
    itemName: 'Hot Water Heater',
    bidPrice: 3000,
    spentToDate: 250,
    categoryComplete: false,
  },
  {
    projectId: 3,
    categoryName: 'Mechanical',
    itemName: 'Gas Lines',
    bidPrice: 5000,
    spentToDate: 4500,
    categoryComplete: true,
  },
  {
    projectId: 4,
    categoryName: 'Mechanical',
    itemName: 'Plumbing',
    bidPrice: 7000,
    spentToDate: 6000,
    categoryComplete: true,
  },
  {
    projectId: 5,
    categoryName: 'Mechanical',
    itemName: 'Furnace',
    bidPrice: 12000,
    spentToDate: 7000,
    categoryComplete: false,
  },
  {
    projectId: 6,
    categoryName: 'Mechanical',
    itemName: 'Hot Water Heater',
    bidPrice: 15000,
    spentToDate: 3000,
    categoryComplete: false,
  },
  {
    projectId: 7,
    categoryName: 'Mechanical',
    itemName: 'Gas Lines',
    bidPrice: 20000,
    spentToDate: 1000,
    categoryComplete: true,
  },
  {
    projectId: 8,
    categoryName: 'Mechanical',
    itemName: 'Plumbing',
    bidPrice: 35000,
    spentToDate: 5000,
    categoryComplete: false,
  },
  {
    projectId: 9,
    categoryName: 'Mechanical',
    itemName: 'Furnace',
    bidPrice: 40000,
    spentToDate: 6500,
    categoryComplete: true,
  },
  {
    projectId: 1,
    categoryName: 'Electrical',
    itemName: 'Breakbox',
    bidPrice: 2500,
    spentToDate: 800,
    categoryComplete: false,
  },
  {
    projectId: 2,
    categoryName: 'Electrical',
    itemName: 'Back-up Generator',
    bidPrice: 3500,
    spentToDate: 2500,
    categoryComplete: false,
  },
  {
    projectId: 3,
    categoryName: 'Electrical',
    itemName: 'Rough Wiring',
    bidPrice: 6000,
    spentToDate: 4500,
    categoryComplete: true,
  },
  {
    projectId: 4,
    categoryName: 'Electrical',
    itemName: 'Final Wiring',
    bidPrice: 8000,
    spentToDate: 600,
    categoryComplete: true,
  },
  {
    projectId: 5,
    categoryName: 'Electrical',
    itemName: 'Breakbox',
    bidPrice: 12000,
    spentToDate: 7000,
    categoryComplete: false,
  },
  {
    projectId: 6,
    categoryName: 'Electrical',
    itemName: 'Back-up Generator',
    bidPrice: 15000,
    spentToDate: 3000,
    categoryComplete: false,
  },
  {
    projectId: 7,
    categoryName: 'Electrical',
    itemName: 'Rough Wiring',
    bidPrice: 20000,
    spentToDate: 1000,
    categoryComplete: true,
  },
  {
    projectId: 8,
    categoryName: 'Electrical',
    itemName: 'Final Wiring',
    bidPrice: 35000,
    spentToDate: 500,
    categoryComplete: false,
  },
  {
    projectId: 9,
    categoryName: 'Electrical',
    itemName: 'Breakbox',
    bidPrice: 40000,
    spentToDate: 6500,
    categoryComplete: true,
  },
];

export function fetchItemsForCategories(
  category: string,
  projectId: number,
): Promise<JobCategoryItemEntry[]> {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      // Simulating a successful data load with a slight delay
      const success = true; // You can toggle this to simulate errors
      if (success) {
        const specifiedItems = ALLJOBCATEGORYITEMS.filter(
          (e) => e.projectId === projectId && category === e.categoryName,
        );
        resolve(specifiedItems);
      } else {
        reject(new Error('Failed to load data'));
      }
    }, 300);
  });
}
